# This pipeline uses the Zephyr Docker image defined here:
# https://github.com/zephyrproject-rtos/docker-image
# It contains all tooling and SDK to build Zephyr based applications
image: zephyrprojectrtos/zephyr-build:latest

pipelines:
  default:
    - step:
        name: 'Lint'
        runs-on:
          - 'self.hosted'
        script:
          - echo "Your linting goes here..."
    - step:
        name: 'Build'
        runs-on:
          - 'self.hosted'
        caches:
          - zephyr
        script:
          - echo "Starting build"
          - unset ZEPHYR_BASE
          - git config --global --add safe.directory $(pwd)/zephyr
          - cd app
          - west update
          - west zephyr-export
            # change this board to yours or set BOARD
            # in CMakeLists.txt file in app directory
          - west build -b nucleo_f302r8
        artifacts:
          - app/build/**
          - zephyr/**
    - step:
        name: 'Test'
        runs-on:
          - 'self.hosted'
        script:
          - echo "Your test goes here..."
          - unset ZEPHYR_BASE
          - git config --global --add safe.directory $(pwd)/zephyr
          - ./zephyr/scripts/twister --platform native_posix_64 -o test-reports -T zephyr/tests/kernel/device
definitions:
  caches:
    zephyr: zephyr
