name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize
        working-directory: app
        run: |
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: app
        run: |
          west build -b myboard

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: app/build/zephyr/zephyr.*
