name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize
        working-directory: app
        run: |
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
          west spdx --init -d build

      - name: Build firmware
        working-directory: app
        run: |
          west build -b myboard

      - name: Build SBOM
        working-directory: app
        run: |
          west spdx -d build

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: app/build/zephyr/zephyr.*

      - name: Archive SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: app/build/spdx/build.spdx

